### PR TITLE
Add public meeting minutes

### PR DESCRIPTION
**Pull request by williamkapke**
Add all approved meeting minutes to-date in markdown format 🎉 .

### CODE REVIEW

**Comment by mikeal** [comment]
What's the best way to also get this into the website? I love that these are in markdown, would be great if we could have them on the website in the same format without managing two copies.

**Comment by williamkapke** [comment]
I was pondering that too.

Do we think that we NEED to list them on the website? Maybe just link the website to this repo instead?

**Comment by joshgav** [comment]
Thanks for these @williamkapke, LGTM, though not sure if the convert script is worth checking in?

Should rvagg be tagged as `TSC` rather than `NodeSource`?

**Comment by williamkapke** [comment]
Because they're legal documents, I decided it might be best to include the uglyscript that I used to changed the formatting of the originals.

And maybe it'll be used again in the future...?

> Should rvagg be tagged as TSC rather than NodeSource?

Personally, I agree. It'd be like tagging @ashleygwilliams as NPM instead of Individual Director! But that's what they did- and, unfortunately, once the board accepts the minutes- we can't change them. 😖

**Pull request merged**
